name: Build & Upload macOS .app

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    env:
      PYTHON_VERSION: 3.11
      APP_NAME: NetworkStats  # adjust to your app's name

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python (${{ matrix.arch }})
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
          architecture: ${{ matrix.arch }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Build Python package (wheel and sdist)
        run: poetry build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Upload build to Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.APP_NAME }}-${{ matrix.arch }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 