name: Build & Upload macOS .app

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    env:
      PYTHON_VERSION: 3.11
      APP_NAME: NetworkStats  # adjust to your app's name

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python (${{ matrix.arch }})
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ matrix.arch }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt py2app

      - name: Build .app bundle
        run: |
          python setup.py py2app

      - name: Zip the .app
        run: |
          zip -r "${{ env.APP_NAME }}-${{ matrix.arch }}.zip" "dist/${{ env.APP_NAME }}.app"

      - name: Upload build to Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.APP_NAME }}-${{ matrix.arch }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 